name: Publish to Comfy registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"

permissions:
  contents: read

jobs:
  publish-node:
    name: Publish Smart Model Loader
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Publish custom node
        uses: Comfy-Org/publish-node-action@d2366e7abb6ab16f3bb03e3520ae25c8cf749bc9
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
